### ISSUE TITLE
Set-IntersightConfiguration broken in 1.0.11.13236

### ISSUE THREAD

**Issue by wgjhstt247** [CiscoDevNet/intersight-powershell#106] opened 2023-08-08 17:12 UTC
**Describe the bug**
Error: Set-IntersightConfiguration: Error performing this operation. Check that BasePath and API Key identifier are configured correctly using the Set-IntersightConfiguration cmdlet.

**To Reproduce**
Follow the steps provided in README to use Set-IntersightConfiguration
```powershell 
Import-Module Intersight.Powershell -RequiredVersion 1.0.11.13236
$config = @{
...fill out parameters here as expected...
}
Set-IntersightConfiguration @config
```

**Version used**
 - Intersight PowerShell Module version: 1.0.11.13236
 - Intersight Appliance Version: 1.0.9-589

**Expected behavior**
Successful response as in Module version 1.0.11.12738

**Additional context**
The same configuration works fine in module version 1.0.11.12738

**Comment by Ghufz** [comment] 2023-08-09 04:22
I am not able to reproduce this issue, Can you provide us the exact error screenshot.
Here is the same cmdlet I have run it.

```powershell
Name              : Intersight.PowerShell
Path              : C:\1.0.11-12236\Intersight\Intersight.PowerShell.dll
Description       : Intersight Powershell module provides the cmdlets to manage, analyze, and automate the IT infrastructure in Intersight.
ModuleType        : Binary
Version           : 1.0.11.13236
PreRelease        :
NestedModules     : {}
ExportedFunctions :
ExportedCmdlets   : {Get-IntersightAaaAuditRecord, Get-IntersightAaaRetentionConfig, Get-IntersightAaaRetentionPolicy, Get-IntersightAccessIpAddress…}
ExportedVariables :
ExportedAliases   :


```
Configure the required parameters

```powershell
$basePath = "https://us-east-1.intersight.com"
$ApiKeyId = "5cd4exxxxxxxxxxx/5ef9bd0e7564612d328ebd60/64a3e20b756461xxxxxxxxxxxxxx"
$ApiKeyFilePath = "C:\\Users\\SecretKey.txt"

 $config = @{
BasePath = $basePath
ApiKeyId = $ApiKeyId
ApiKeyFilePath = $ApiKeyFilePath
HttpSigningHeader =  @("(request-target)", "Host", "Date", "Digest")
Set-IntersightConfiguration @config
```

**Comment by wgjhstt247** [comment] 2023-08-09 16:48
For security reasons, I've crossed out sensitive information, but here's what I'm doing. I'm using a CVA appliance deployed locally.
![image](https://github.com/CiscoDevNet/intersight-powershell/assets/802507/762c9376-2433-43f3-a5b1-fe42a19181dd)
![image](https://github.com/CiscoDevNet/intersight-powershell/assets/802507/f0d804bf-2dbd-4465-9199-9c79d96dec7f)
![image](https://github.com/CiscoDevNet/intersight-powershell/assets/802507/7fbbaf48-04f4-4042-93de-9b71f48ce72b)

**Comment by wgjhstt247** [comment] 2023-08-09 22:21
![image](https://github.com/CiscoDevNet/intersight-powershell/assets/802507/74ed6191-b677-4bc6-b041-8a9aca9601f2)
<json_output_for_organization_list>
![image](https://github.com/CiscoDevNet/intersight-powershell/assets/802507/6f3397a0-4af2-46d3-9a58-c350ab94d5a1)

**Comment by Ghufz** [comment] 2023-08-11 05:24
It seems the old RestSgarp.dll is being used in you powershell session.
Can you run the follwoing cmdlet to check the issue is common for all cmdlets.

```Powershell
# once you run Set-IntersightConfiguration please execute below cmdlet and check whether it works or same exception has been thrown like before.

Get-IntersightConfiguration # to check the Intersight Configuration.

Get-IntersightNtpPolicy

Get-IntersightManagedObject -ObjectType organization.Organization

```

**Comment by wgjhstt247** [comment] 2023-08-16 12:26
- `Get-IntersightConfiguration`: Shows the correct output with the expected configuration
- `Get-IntersightNtpPolicy`: The JSON string {<ntp_policy_objects>} cannot be deserialized into any schema defined
- `Get-IntersightManagedObject -ObjectType organization.Organization`: No error. The output is in JSON format.

**Comment by Ghufz** [comment] 2023-08-17 04:38
It seems the exception is caused due to the  object received from the server, Can you check the ``` Get-IntersightOrganizationOrganization``` here also you may encounter the same error multiple schema matched. 

Please check the data on server side that any Mo is missing objectType or ClassId or any enum  has the value which is not supported now.

**Comment by wgjhstt247** [comment] 2023-08-22 18:45
The same server side data returned by `Get-IntersightOrganizationOrganization` works fine with the previous version of the powershell module. That said, I noticed that 'VersionContext' and 'DisplayNames' are not present on the objects returned from the Server with default parameters.

There are no MoIds, objectType, or ClassId properties values missing.

**Comment by Ghufz** [comment] 2023-09-11 04:40
@wgjhstt247  Did you tried with the latest Intersight.PowerShell module?

**Comment by wgjhstt247** [comment] 2023-09-11 18:34
In version 1.0.11.13376 - Yes, same result.

**Comment by wgjhstt247** [comment] 2023-10-13 18:25
@Ghufz This is still broken. Please fix this.
- Intersight CVA version: 1.0.9-615
- Intersight.Powershell version: 1.0.11.13515

**Comment by Ghufz** [comment] 2024-03-20 09:12
Please follow the workaround suggested by https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.4#use-the-dependency-out-of-process

Refer to Section Use the dependency out of process

**Closed by Ghufz** 2024-03-20 09:12 UTC

**Comment by wgjhstt247** [comment] 2024-06-26 19:01
@Ghufz This is still not working and is not a dependency issue for our CVA installation. No other modules are loaded in my powershell session when I try to run Set-IntersightConfiguration
